language: python
python:
  - 3.6
  - 2.7

sudo: false

env:
  matrix:
    - TEST_DIR=tests

# Setup anaconda
before_install:
# Install packages
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
      wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/anaconda/bin:/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
      conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib;
    else
      conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib;
    fi
  - pip install -r requirements-dev.txt
  - python setup.py install

# Run test
script:
  - nosetests $TEST_DIR --with-cov --cov processing --cov-config .coveragerc -v -s;

# Calculate coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)

# notify slack
notifications:
  slack: simpeg:1KZq5giMtlJJ58TijIPgqf7n
